name: Bug Report
description: Report a bug or issue with AquaGuard
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us resolve it quickly.
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you using? (e.g., 1.20.1)
      placeholder: e.g., 1.20.1
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: Forge Version
      description: What version of Forge are you using? (e.g., 47.1.0)
      placeholder: e.g., 47.1.0
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: AquaGuard Version
      description: What version of AquaGuard are you using? (e.g., 1.0.0)
      placeholder: e.g., 1.0.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: e.g., When I use /ag rollback, the server crashes.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue.
      placeholder: |
        1. Start a server with AquaGuard.
        2. Run /ag rollback user <player> 1h.
        3. Observe crash.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: e.g., The rollback should complete without crashing.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or Crash Report
      description: Paste relevant logs or crash reports (use a pastebin link if lengthy).
      placeholder: e.g., Link to crash report: https://pastebin.com/xyz
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details, such as other mods installed or server setup.
      placeholder: e.g., Running with 5 other mods, dedicated server.
